### ISSUE TITLE
Clone til download

### ISSUE THREAD

**Issue by poul5553** [iskariotdk/echotea#12]
Lav en clone til hvert udviklingsmiljø

**Comment by poul5553** [comment]
Lav branch til udvikling

**Comment by CosmicNoon** [comment]
branches til **alt** slags udvikling (html, css, js. Design/Smaller edits bør få branches så vi ikke overskrider kode der bliver lavet/blev lavet after)

så lav branch_es_ til udvikling ;)

**Comment by iskariotdk** [comment]
Tænker at hver branch indeholder tilhørende css/js filer, så vi dermed ikke får for mange branch

**Comment by poul5553** [comment]
Afsluttet
