### ISSUE TITLE
Lav et layout til hjemmesiden

### ISSUE THREAD

**Issue by poul5553** [iskariotdk/echotea#20]
Oplæg for eksempel i photoshop. 
Skal visualisere hjemmesiden så kunden har noget konkret at forholde sig til.

**Comment by iskariotdk** [comment]
Wireframe

**Comment by koyangidees** [comment]
![Uploading eco.jpg…]()

**Comment by koyangidees** [comment]
![eco_edit](https://user-images.githubusercontent.com/39299659/44138921-c91e9dca-a075-11e8-9fac-b372481ce7a7.jpg)
